from cwaffles/openpose:latest

RUN apt-get -y install locales nano less


RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8 

RUN pip3 install pandas scikit-learn tqdm matplotlib colorama

WORKDIR /app

COPY . .

WORKDIR /app/LibrasDB

# ENTRYPOINT ["sh", "entrypoint.sh"]
